apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  RABBITMQ_SERVER: rabbitmq-service
  RABBITMQ_PORT: "5672"
  NOTIFICATION_USER_CREATED_QUEUE: "notifications-user-created"
  NOTIFICATION_PAYMENT_FAILED_QUEUE: "notifications-payment-failed"
  NOTIFICATION_PAYMENT_PROCESSED_QUEUE: "notifications-payment-processed"
  NOTIFICATION_DELIVERY_FAILED_QUEUE: "notification-delivery-failed"
  REDIS_SERVER: redis-service
  REDIS_PORT: "6379" 
  REDIS_NAME: "FiapCloudGames:" 
  ENVIRONMENT: "Development"
  MASSTRANSIT_USAGE_TELEMETRY: "false"